Add first Behat scenario for API
Setono/SyliusGiftCardPlugin pull request #149
Opened 2021-09-01 11:57 UTC by Roshyo

2021-09-01 11:59 UTC, loevgaard requested changes
Can you check which services needs to be public? I am pretty sure it's only the pages or something

2021-09-01 11:59 UTC, loevgaard commented on tests/Behat/Resources/api/clients.xml
> +        <defaults public="true"/>
Does this needs to be public?

2021-09-01 11:59 UTC, loevgaard commented on tests/Behat/Resources/context/api.xml
> +        <defaults public="true"/>
Does this needs to be public?

2021-09-01 11:59 UTC, loevgaard commented on tests/Behat/Resources/context/setup.xml
> +        <defaults public="true"/>
Does this needs to be public?

2021-09-01 14:37 UTC, Roshyo commented
Indeed, only the Contexts need to be public. Pages and api client can be private

2021-09-02 06:43 UTC, loevgaard approved these changes

2021-09-02 13:54 UTC, merged