Php 8.1 / Sylius 1.12 compatible
Setono/SyliusGiftCardPlugin pull request #265
Opened 2024-10-07 15:56 UTC by ehibes

2024-10-07 16:21 UTC, Prometee commented on src/Applicator/GiftCardApplicator.php
> +        if (!$orderChannel instanceof ChannelInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee requested changes

2024-10-07 16:53 UTC, Prometee commented on src/Applicator/GiftCardApplicator.php
> +        if (!$orderChannel instanceof ChannelInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Applicator/GiftCardApplicator.php
> +        if (!$giftCard instanceof GiftCardInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/EmailManager/GiftCardEmailManager.php
> +        if (!$customer instanceof \Sylius\Component\Customer\Model\CustomerInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/EmailManager/GiftCardEmailManager.php
> +        if (!$channel instanceof ChannelInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/EventSubscriber/SendEmailWithGiftCardToCustomerSubscriber.php
> +        if (!$customer instanceof CustomerInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Form/DataTransformer/GiftCardToCodeDataTransformer.php
> +        if ($giftCard instanceof GiftCardInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Generator/GiftCardCodeGenerator.php
> +            $code = mb_strtoupper(mb_substr((string) $code, 0, $this->codeLength));
Asserting to check for string can avoid some issue in case the code is not already a string

2024-10-07 16:53 UTC, Prometee commented on src/Generator/GiftCardCodeGenerator.php
> +        return $this->giftCardRepository->findOneByCode($code) instanceof GiftCardInterface;
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Model/GiftCard.php
> +        return !$this->orderItemUnit instanceof OrderItemUnitInterface;
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Model/GiftCard.php
> +        if (!$orderItemUnit instanceof OrderItemUnitInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Model/GiftCard.php
> +        if (!$customer instanceof CustomerInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Model/GiftCard.php
> +        if (!$order instanceof OrderInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Model/GiftCard.php
> +        if (!$channel instanceof ChannelInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Model/GiftCard.php
> +        if (!$date instanceof DateTimeInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Model/GiftCard.php
> +        if (!$giftCardValidUntil instanceof DateTimeInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Provider/GiftCardConfigurationProvider.php
> +        if ($configuration instanceof GiftCardConfigurationInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Provider/GiftCardConfigurationProvider.php
> +        if ($configuration instanceof GiftCardConfigurationInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Provider/GiftCardConfigurationProvider.php
> +            $localeCode = $order instanceof OrderInterface ? $order->getLocaleCode() : $this->localeContext->getLocaleCode();
```suggestion
            $localeCode = $this->localeContext->getLocaleCode();
            if ($order instanceof OrderInterface) {
                $localeCode = $order->getLocaleCode();
            }
```

2024-10-07 16:53 UTC, Prometee commented on src/Renderer/PdfRenderer.php
> +        if (!$channel instanceof ChannelInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Renderer/PdfRenderer.php
> +            if ($order instanceof OrderInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Renderer/PdfRenderer.php
> +            if (!$channel instanceof ChannelInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Renderer/PdfRenderer.php
> +            if ($order instanceof OrderInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Renderer/PdfRenderer.php
> +        if (!$giftCardConfiguration instanceof GiftCardConfigurationInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Resolver/CustomerChannelResolver.php
> +        if ($latestOrder instanceof OrderInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Resolver/CustomerChannelResolver.php
> +            if ($channel instanceof \Sylius\Component\Channel\Model\ChannelInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Resolver/LocaleResolver.php
> +        if ($latestOrder instanceof \Setono\SyliusGiftCardPlugin\Model\OrderInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Resolver/LocaleResolver.php
> +        if ($channel instanceof \Sylius\Component\Channel\Model\ChannelInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Resolver/LocaleResolver.php
> +        if ($locale instanceof LocaleInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Security/GiftCardVoter.php
> +        if (!$giftCard->getCustomer() instanceof CustomerInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Serializer/Normalizer/GiftCardConfigurationNormalizer.php
> +        if ($request instanceof Request) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Serializer/Normalizer/GiftCardConfigurationNormalizer.php
> +        if (!$image instanceof GiftCardConfigurationImageInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Serializer/Normalizer/GiftCardConfigurationNormalizer.php
> +        if (null !== $path && $request instanceof Request) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Validator/Constraints/DefaultGiftCardConfigurationMustExistValidator.php
> +        if (!$defaultGiftCardConfiguration instanceof GiftCardConfigurationInterface || $defaultGiftCardConfiguration->getId() === $value->getId()) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Validator/Constraints/HasBackgroundImageValidator.php
> +        if (!$backgroundImage instanceof GiftCardConfigurationImageInterface) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on src/Validator/Constraints/HasBackgroundImageValidator.php
> +        if (!$backgroundImage->getFile() instanceof SplFileInfo && null === $backgroundImage->getPath()) {
Keeping null test is better and quicker to understand, IMHO.

2024-10-07 16:53 UTC, Prometee commented on tests/Application/config/bundles.php
I guess this is coming from Rector, but it's easier to read the full class name instead of searching for the `use` reference in this particular file.

2024-10-07 16:53 UTC, Prometee commented on tests/Behat/Context/Setup/GiftCardContext.php
> +        if (!$channel instanceof ChannelInterface) {
Keeping null test is better and quicker to understand, IMHO.

2025-05-20 06:06 UTC, closed without merging

2025-10-16 08:01 UTC, Valmonzo commented
Hello, will the plugin be compatible with version 1.12, or will it no longer be maintained? 😢